// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package v1

import (
	"github.com/dabao-zhao/xgin-layout/app/helloworld/v1/biz"
	"github.com/dabao-zhao/xgin-layout/app/helloworld/v1/data"
	"github.com/dabao-zhao/xgin-layout/app/helloworld/v1/handlers"
	"github.com/dabao-zhao/xgin-layout/app/helloworld/v1/services"
	"github.com/dabao-zhao/xgin-layout/config"
	"github.com/op/go-logging"
)

// Injectors from wire.go:

func InitializeGreeterHandler(configConfig *config.Config, logger *logging.Logger) *handlers.GreeterHandler {
	db := data.NewDB(configConfig)
	dataData := data.NewData(db)
	greeterRepo := data.NewGreeterRepo(dataData, logger)
	greeterUsecase := biz.NewGreeterUsecase(greeterRepo, logger)
	greeterService := services.NewGreeterService(greeterUsecase, logger)
	greeterHandler := handlers.NewGreeterHandler(greeterService, logger)
	return greeterHandler
}
